import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import Header from '@/components/layout/Header';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Use specific weights
  variable: "--font-poppins", // Define a CSS variable
  display: "swap",
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >

        <Header />
        {children}
      </body>
    </html>
  );
}
